Cannot exec 'logs.py': No such file or directory
(u'0.00321002', u'0.00322300', 0.00321299)
(u'0.00320181', u'0.00322300', 0.003214)
(u'0.00320000', u'0.00322300', 0.003214)
(u'0.00320181', u'0.00322300', 0.003214)
(u'0.00322605', u'0.00322300', 0.003214)
(u'0.00322604', u'0.00323300', 0.003199)
(u'0.00322604', u'0.00324100', 0.003199)
(u'0.00322604', u'0.00324100', 0.003199)
(u'0.00322604', u'0.00324100', 0.003199)
(u'0.00322604', u'0.00325800', 0.003199)
(u'0.00322606', u'0.00323900', 0.003199)
(u'0.00324214', u'0.00325100', 0.003199)
(u'0.00324214', u'0.00325800', 0.003199)
(u'0.00324214', u'0.00324500', 0.003199)
(u'0.00324214', u'0.00325800', 0.003199)
(u'0.00324214', u'0.00325000', 0.003199)
(u'0.00325671', u'0.00325000', 0.003199)
(u'0.00325671', u'0.00325000', 0.003199)
(u'0.00325671', u'0.00324900', 0.003199)
(u'0.00325671', u'0.00324900', 0.003199)
(u'0.00325671', u'0.00324900', 0.003199)
(u'0.00321944', u'0.00324800', 0.003199)
(u'0.00321944', u'0.00324800', 0.00315962)
(u'0.00323045', u'0.00324800', 0.00315962)
(u'0.00323045', u'0.00323000', 0.00315962)
(u'0.00323045', u'0.00324400', 0.00315962)
(u'0.00323044', u'0.00324200', 0.00315962)
(u'0.00323044', u'0.00324000', 0.00315962)
(u'0.00323044', u'0.00323800', 0.00315962)
(u'0.00323044', u'0.00323800', 0.00315962)
(u'0.00323044', u'0.00322500', 0.00315962)
(u'0.00323044', u'0.00322300', 0.00315962)
